from zabbixproxy.tasks.agent_deployment import deploy_zabbix_agent_task
from zabbixproxy.tasks.host_creation import create_zabbix_host_task
from zabbixproxy.tasks.host_record import create_zabbix_host_record_task
from zabbixproxy.tasks.workflow import create_host_workflow