tcp_service_checks = [
    {
        "name": "Check HTTP on port 80",
        "key_": "net.tcp.service[http,,80]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if HTTP service is responding on port 80",
    },
    {
        "name": "Check HTTPS on port 443",
        "key_": "net.tcp.service[https,,443]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if HTTPS service is responding on port 443",
    },
    {
        "name": "Check SSH on port 22",
        "key_": "net.tcp.service[ssh,,22]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if SSH service is responding on port 22",
    },
    {
        "name": "Check MySQL on port 3306",
        "key_": "net.tcp.service[mysql,,3306]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if MySQL service is responding on port 3306",
    },
    {
        "name": "Check FTP on port 21",
        "key_": "net.tcp.service[ftp,,21]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if FTP service is responding on port 21",
    },
]

udp_service_checks = [
    {
        "name": "Check DNS on UDP port 53",
        "key_": "net.udp.service[dns,,53]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if DNS service is responding on UDP port 53",
    },
    {
        "name": "Check NTP on UDP port 123",
        "key_": "net.udp.service[ntp,,123]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if NTP service is responding on UDP port 123",
    },
    {
        "name": "Check SNMP on UDP port 161",
        "key_": "net.udp.service[snmp,,161]",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if SNMP service is responding on UDP port 161",
    },
]

icmp_hecks = [
    {
        "name": "Host ICMP Ping Status",
        "key_": "icmpping",
        "type": 3,
        "value_type": 3,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "description": "Checks if the host is up using ICMP ping (1 = up, 0 = down)",
    },
    {
        "name": "Ping Response Time (avg)",
        "key_": "icmppingavg",
        "type": 3,
        "value_type": 0,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "units": "s",
        "description": "Average ICMP ping response time in seconds",
    },
    {
        "name": "Ping Packet Loss",
        "key_": "icmppingloss",
        "type": 3,
        "value_type": 0,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "units": "%",
        "description": "ICMP ping packet loss percentage",
    },
    {
        "name": "Ping Max Response Time",
        "key_": "icmppingmax",
        "type": 3,
        "value_type": 0,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "units": "s",
        "description": "Maximum ICMP ping response time",
    },
    {
        "name": "Ping Min Response Time",
        "key_": "icmppingmin",
        "type": 3,
        "value_type": 0,
        "interfaceid": "<INTERFACE_ID>",
        "delay": "60s",
        "history": "7d",
        "trends": "30d",
        "units": "s",
        "description": "Minimum ICMP ping response time",
    },
]
