#ansibal/playbooks/playbook.yml
---
- hosts: all
  become: true
  become_method: sudo

  collections:
    - community.docker
  tasks:
    # Cleanup tasks with tag for selective execution
    - name: CLEANUP - Stop Nginx container
      community.docker.docker_container:
        name: nginx
        state: stopped
      ignore_errors: true
      tags: cleanup

    - name: CLEANUP - Remove Nginx container
      community.docker.docker_container:
        name: nginx
        state: absent
      ignore_errors: true
      tags: cleanup

    # Original installation tasks
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
      tags: install

    - name: Pull Nginx image
      community.docker.docker_image:
        name: nginx
        source: pull
      tags: install

    - name: Create Nginx container
      community.docker.docker_container:
        name: nginx
        image: nginx:latest
        ports:
          - "{{ port }}:80"
        state: started
      tags: install
